services:
  database:
    image: postgres
    restart: always
    ports:
      - ${DATABASE_PORT}:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - database_data:/var/lib/postgresql/data

volumes:
  database_data:
